In [8]:
import torch
import polars as pl
import numpy as np
import gc
from tqdm.auto import tqdm
from sklearn.preprocessing import MultiLabelBinarizer
from transformers import (AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments)
import os
from torch import nn
from huggingface_hub import login, HfApi
from sklearn.metrics import jaccard_score, classification_report

In [17]:
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        if "habr_cleaned" in filename:
            DATA_PATH = os.path.join(dirname, filename)

df = pl.read_parquet(DATA_PATH)

mlb = MultiLabelBinarizer()
labels_matrix = mlb.fit_transform(df["hubs_filtered"].to_list())
model_name = "intfloat/multilingual-e5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [18]:
class HabrDataset(torch.utils.data.Dataset):
    def __init__(self, texts, labels, tokenizer):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        text = "query: " + str(self.texts[idx])[:3000]
        encoding = self.tokenizer(
            text, truncation=True, padding='max_length',
            max_length=512, return_tensors='pt'
        )
        return {
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'labels': torch.tensor(self.labels[idx], dtype=torch.float)
        }

total_available = len(df["text_clean"])
val_size = 1000
train_limit = total_available - val_size
if train_limit <= 0:
    train_limit = int(total_available * 0.9)

all_texts = df["text_clean"].to_list()
train_texts = all_texts[:train_limit]
val_texts = all_texts[train_limit:]
train_labels = labels_matrix[:train_limit]
val_labels = labels_matrix[train_limit:]
train_dataset = HabrDataset(train_texts, train_labels, tokenizer)
val_dataset = HabrDataset(val_texts, val_labels, tokenizer)

print(f"len train = {len(train_dataset)}, len val={len(val_dataset)}")

len train = 70183, len val=1000

In [11]:
del all_texts, train_texts, val_texts
del df
gc.collect()
torch.cuda.empty_cache()

In [3]:
len(train_dataset)

70183

In [4]:
len(val_dataset)

1000

# **Для начала посмотрим как обучится на 2 эпохах, чтобы было понимание как все работает и чтоб подобрать параметры**

In [5]:
model = AutoModelForSequenceClassification.from_pretrained(
    model_name, 
    num_labels=len(mlb.classes_),
    problem_type="multi_label_classification"
).to("cuda")

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: intfloat/multilingual-e5-small
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [3]:
training_args = TrainingArguments(
    output_dir='./results_e5',
    num_train_epochs=2,
    per_device_train_batch_size=16, 
    gradient_accumulation_steps=2,
    fp16=True,
    learning_rate=5e-5,
    lr_scheduler_type="cosine",
    warmup_ratio=0.1,
    logging_steps=100,
    eval_strategy="epoch",
    save_strategy="no",
    report_to="none"
)

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: intfloat/multilingual-e5-small
Key                     | Status     |
------------------------+------------+-
embeddings.position_ids | UNEXPECTED |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

In [4]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset
)

trainer.train()

model.save_pretrained("./habr_e5_model")
tokenizer.save_pretrained("./habr_e5_model")

Начинаю обучение на 2 GPU...

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./habr_e5_model/tokenizer_config.json', './habr_e5_model/tokenizer.json')

## **Большая моделька**

In [12]:
all_labels = []
for i in range(len(train_dataset)):
    all_labels.append(train_dataset.labels[i])

labels_matrix = np.stack(all_labels)
print(labels_matrix.shape)

(70183, 429)

**##добавим балансировку весов для хабов, тк их частотность разная#**

In [12]:
counts = labels_matrix.sum(axis=0)
total_samples = len(labels_matrix)
pos_weights = (total_samples - counts) / (counts + 1e-5)
pos_weights = np.clip(pos_weights, 1, 50) 
pos_weights_tensor = torch.tensor(pos_weights, dtype=torch.float).to("cuda")

In [ ]:
class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")
        loss_fct = nn.BCEWithLogitsLoss(pos_weight=pos_weights_tensor)
        loss = loss_fct(logits, labels)
        return (loss, outputs) if return_outputs else loss

In [13]:
training_args = TrainingArguments(
    output_dir='./results_weighted',
    num_train_epochs=5,             
    per_device_train_batch_size=32, 
    fp16=True,
    learning_rate=1e-4,
    lr_scheduler_type="cosine",
    logging_steps=50,
    report_to="none"
)


trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset
)

trainer.train()

Запуск взвешенного обучения...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=5565, training_loss=0.46286458386458046, metrics={'train_runtime': 8429.3802, 'train_samples_per_second': 42.223, 'train_steps_per_second': 0.66, 'total_flos': 2.362483744363008e+16, 'train_loss': 0.46286458386458046, 'epoch': 5.0})

In [14]:
model.save_pretrained("./habr_e5_final")
tokenizer.save_pretrained("./habr_e5_final")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./habr_e5_final/tokenizer_config.json', './habr_e5_final/tokenizer.json')

In [20]:
login("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")
repo_id = "Yalmess/habr-e5-classifier"

print(f"Загрузка модели в репозиторий {repo_id}...")

model.push_to_hub(repo_id)
tokenizer.push_to_hub(repo_id)

Загрузка модели в репозиторий Yalmess/habr-e5-classifier...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

README.md: 0.00B [00:00, ?B/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

Готово! Теперь твоя модель живет на Hugging Face.

In [13]:
# mlb = MultiLabelBinarizer()
# labels_matrix = mlb.fit_transform(df["hubs_filtered"].to_list())
# total_available = len(df)
# val_size = 1000
# train_limit = total_available - val_size

# all_texts = df["text_clean"].to_list()
# train_texts = all_texts[:train_limit]
# val_texts = all_texts[train_limit:]
# train_labels = labels_matrix[:train_limit]
# val_labels = labels_matrix[train_limit:]
# train_dataset = HabrDataset(train_texts, train_labels, tokenizer)
# val_dataset = HabrDataset(val_texts, val_labels, tokenizer)

# del all_texts
# gc.collect()

In [14]:
MODEL_NAME = "Yalmess/habr-e5-classifier"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME).to(DEVICE)

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [19]:
def evaluate_fasttext_style(model, texts, labels, tokenizer, batch_size=16):
    model.eval()
    p1, r1, j3 = 0, 0, 0
    n = len(texts)   
    for i in tqdm(range(0, n, batch_size)):
        batch_texts = ["query: " + str(t)[:2000] for t in texts[i:i+batch_size]]
        batch_labels = labels[i:i+batch_size]
        inputs = tokenizer(batch_texts, truncation=True, padding=True, 
                           max_length=512, return_tensors="pt").to(DEVICE)
        
        with torch.no_grad():
            outputs = model(**inputs)
            probs = torch.sigmoid(outputs.logits).cpu().numpy()
            
        for j in range(len(probs)):
            true_idx = np.where(batch_labels[j] == 1)[0]
            top_idx = np.argsort(probs[j])[::-1]
            if top_idx[0] in true_idx:
                p1 += 1
                r1 += (1 / len(true_idx))
            top3 = set(top_idx[:3])
            true_set = set(true_idx)
            j3 += len(top3 & true_set) / len(top3 | true_set)
            
    print(f"Precision@1: {p1/n:.4f}")
    print(f"Recall@1:    {r1/n:.4f}")
    print(f"Jaccard@3:   {j3/n:.4f}")

evaluate_fasttext_style(model, val_texts, val_labels, tokenizer)

  0%|          | 0/63 [00:00<?, ?it/s]

Precision@1: 0.2170
Recall@1:    0.0805
Jaccard@3:   0.0996

In [37]:
# def get_predictions(model, dataset, batch_size=32):
#     model.eval()
#     device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#     model.to(device)
    
#     all_probs = []
#     all_labels = []
    
#     with torch.no_grad():
#         for i in tqdm(range(0, len(dataset), batch_size)):
#             batch_input_ids = []
#             batch_target_labels = []
            
#             for j in range(i, min(i + batch_size, len(dataset))):
#                 item = dataset[j]
#                 batch_input_ids.append(item['input_ids'])
#                 batch_target_labels.append(item['labels'])

#             input_ids = torch.stack(batch_input_ids).to(device)
#             labels = torch.stack(batch_target_labels).numpy()
#             outputs = model(input_ids)
#             logits = outputs.logits
#             probs = torch.sigmoid(logits).cpu().numpy()
            
#             all_probs.append(probs)
#             all_labels.append(labels)
            
#     return np.vstack(all_probs), np.vstack(all_labels)

# y_probs, y_true = get_predictions(model, val_dataset)

# best_threshold = 0.3
# best_jaccard = 0
# thresholds = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

# for t in thresholds:
#     y_pred = (y_probs > t).astype(int)
#     score = jaccard_score(y_true, y_pred, average='samples', zero_division=0)
#     print(f"Threshold: {t:.1f} | Jaccard Score: {score:.4f}")
    
#     if score > best_jaccard:
#         best_jaccard = score
#         best_threshold = t

# print(f"\топ порог: {best_threshold} (жаккард={best_jaccard:.4f})")
# print(f"\n---Threshold {best_threshold} ---")
# final_preds = (y_probs > best_threshold).astype(int)
# report = classification_report(
#     y_true, 
#     final_preds, 
#     target_names=mlb.classes_, 
#     zero_division=0,
#     digits=4
# )
# print("\n".join(report.split("\n")[-10:]))

  0%|          | 0/32 [00:00<?, ?it/s]

Threshold: 0.1 | Jaccard Score: 0.0198
Threshold: 0.2 | Jaccard Score: 0.0295
Threshold: 0.3 | Jaccard Score: 0.0400
Threshold: 0.4 | Jaccard Score: 0.0520
Threshold: 0.5 | Jaccard Score: 0.0643
Threshold: 0.6 | Jaccard Score: 0.0812
Threshold: 0.7 | Jaccard Score: 0.0979
Threshold: 0.8 | Jaccard Score: 0.0787
\топ порог: 0.7 (жаккард=0.0979)

---Threshold 0.7 ---
                                     электроника для начинающих     0.0972    1.0000    0.1772         7
                                     энергия и элементы питания     0.0891    0.6429    0.1565        14
                                                      я пиарюсь     0.0000    0.0000    0.0000         1
                                                     яндекс api     0.0000    0.0000    0.0000         0

                                                      micro avg     0.1118    0.3204    0.1658      3327
                                                      macro avg     0.0174    0.1026    0.0280      3327
                                                   weighted avg     0.0907    0.3204    0.1291      3327
                                                    samples avg     0.1146    0.3455    0.1636      3327

In [20]:
def predict_hubs(text, model, tokenizer, mlb, threshold=0.3):
    model.eval()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    text_prepared = "query: " + str(text)[:3000]
    inputs = tokenizer(
        text_prepared, 
        return_tensors="pt", 
        truncation=True, 
        padding='max_length', 
        max_length=512
    ).to(device)
    with torch.no_grad():
        outputs = model(**inputs)
        probs = torch.sigmoid(outputs.logits).cpu().numpy()[0]
    predicted_indices = [i for i, p in enumerate(probs) if p > threshold]
    if not predicted_indices:
        predicted_indices = [np.argmax(probs)]
    result_matrix = np.zeros((1, len(mlb.classes_)))
    for idx in predicted_indices:
        result_matrix[0, idx] = 1
        
    predicted_labels = mlb.inverse_transform(result_matrix)[0]
    sorted_res = sorted(
        [(mlb.classes_[i], probs[i]) for i in predicted_indices], 
        key=lambda x: x[1], 
        reverse=True
    )
    
    return sorted_res

sample_text = """
Сегодня мы разберем, как развернуть контейнеры Docker в облаке AWS с использованием Terraform. 
Мы напишем конфигурацию для кластера Kubernetes (EKS) и настроим CI/CD через GitHub Actions.
"""

results = predict_hubs(sample_text, model, tokenizer, mlb, threshold=0.3)
for hub, prob in results:
    print(f"{hub}: {prob:.2%}")

devops: 84.94%
java: 78.34%
программирование: 77.32%
разработка мобильных приложений: 77.07%
блог компании otus: 76.78%
android: 75.31%
kubernetes: 75.09%
конференции: 74.67%
веб-разработка: 73.53%
ios: 72.98%
python: 72.72%
open source: 72.52%
тестирование it-систем: 71.99%
тестирование веб-сервисов: 71.33%
javascript: 70.22%
системное администрирование: 70.14%
.net: 69.55%
c++: 67.89%
серверное администрирование: 67.84%
c#: 66.53%
высоконагруженные системы: 64.58%
управление разработкой: 64.41%
базы данных: 64.37%
блог компании ruvds.com: 64.35%
анализ и проектирование систем: 63.85%
php: 62.79%
блог компании vk: 61.44%
блог компании jug ru group: 60.22%
go: 60.20%
проектирование и рефакторинг: 60.05%
микросервисы: 59.61%
блог компании microsoft: 59.38%
sql: 59.20%
учебный процесс в it: 58.53%
проектирование api: 58.53%
прочее: 58.46%
блог компании конференции олега бунина (онтико): 57.48%
алгоритмы: 55.46%
big data: 55.38%
блог компании флант: 54.09%
*nix: 53.28%
блог компании слёрм: 53.27%
linux: 53.26%
windows: 52.75%
тестирование мобильных приложений: 52.72%
качество кода: 51.97%
c: 51.75%
swift: 51.41%
it-инфраструктура: 48.79%
git: 48.75%
облачные сервисы: 48.35%
html: 47.14%
kotlin: 46.75%
node.js: 46.11%
виртуализация: 46.01%
интерфейсы: 45.78%
системное программирование: 45.73%
хранение данных: 45.08%
ненормальное программирование: 44.82%
настройка linux: 44.30%
postgresql: 43.74%
разработка игр: 43.64%
github: 43.38%
карьера в it-индустрии: 42.39%
блог компании издательский дом «питер»: 41.25%
блог компании inlyit: 40.48%
веб-дизайн: 40.47%
microsoft azure: 39.60%
css: 39.20%
блог компании pvs-studio: 38.90%
компиляторы: 38.65%
блог компании яндекс: 38.24%
математика: 37.97%
rust: 37.59%
reactjs: 36.78%
визуализация данных: 36.67%
дизайн мобильных приложений: 36.32%
браузеры: 36.08%
apache: 36.03%
блог компании badoo: 35.82%
профессиональная литература: 35.59%
машинное обучение: 35.25%
управление проектами: 34.96%
ооп: 34.47%
блог компании jetbrains: 33.73%
microsoft sql server: 33.62%
распределённые системы: 33.40%
visual studio: 33.24%
дизайн: 33.07%
облачные вычисления: 32.81%
блог компании avitotech: 32.73%
софт: 32.68%
системы сборки: 32.60%
функциональное программирование: 32.18%
отладка: 32.02%
блог компании skillfactory: 31.90%
блог компании skillbox: 31.84%
блог компании т-банк: 31.38%
управление продуктом: 30.90%
data engineering: 30.72%

In [21]:
sample_text_1 = """
В этой статье мы изучим основы SwiftUI и архитектуры MVVM. 
Разберем, как использовать Combine для обработки сетевых запросов и 
почему управление состоянием через @StateObject лучше старых подходов в UIKit.
"""

results = predict_hubs(sample_text_1, model, tokenizer, mlb, threshold=0.3)
for hub, prob in results:
    print(f"{hub}: {prob:.2%}")

java: 85.78%
javascript: 83.42%
программирование: 82.39%
веб-разработка: 82.19%
.net: 79.65%
блог компании otus: 78.51%
devops: 77.90%
c++: 77.01%
c#: 76.44%
android: 76.22%
php: 75.49%
разработка мобильных приложений: 75.18%
ios: 72.93%
блог компании ruvds.com: 72.08%
open source: 70.88%
kubernetes: 69.23%
sql: 67.86%
python: 66.94%
базы данных: 66.70%
высоконагруженные системы: 66.36%
конференции: 65.93%
postgresql: 65.78%
go: 64.96%
html: 64.42%
тестирование веб-сервисов: 63.79%
reactjs: 63.25%
css: 63.08%
тестирование it-систем: 62.73%
kotlin: 62.27%
блог компании jug ru group: 61.98%
блог компании microsoft: 61.08%
проектирование и рефакторинг: 60.94%
блог компании pvs-studio: 60.32%
node.js: 59.81%
swift: 58.32%
системное администрирование: 56.66%
блог компании vk: 56.40%
качество кода: 56.16%
c: 55.84%
микросервисы: 55.25%
серверное администрирование: 54.30%
прочее: 53.95%
анализ и проектирование систем: 53.13%
проектирование api: 52.31%
блог компании флант: 50.22%
windows: 49.37%
typescript: 48.87%
компиляторы: 47.86%
блог компании слёрм: 47.08%
visual studio: 47.00%
ненормальное программирование: 46.73%
блог компании конференции олега бунина (онтико): 46.35%
git: 46.22%
ооп: 46.04%
linux: 45.79%
управление разработкой: 45.51%
учебный процесс в it: 45.30%
алгоритмы: 45.01%
rust: 44.35%
блог компании издательский дом «питер»: 43.93%
функциональное программирование: 43.47%
тестирование мобильных приложений: 42.68%
системное программирование: 41.16%
flutter: 39.34%
*nix: 38.86%
big data: 38.15%
блог компании jetbrains: 37.33%
системы сборки: 36.90%
laravel: 36.41%
angular: 36.13%
хранение данных: 36.02%
github: 35.92%
блог компании т-банк: 35.46%
microsoft sql server: 35.37%
блог компании badoo: 35.37%
vuejs: 35.14%
профессиональная литература: 34.95%
it-инфраструктура: 34.49%
веб-дизайн: 34.34%
интерфейсы: 32.84%
облачные сервисы: 32.79%
apache: 32.09%
виртуализация: 32.05%
django: 31.46%
блог компании яндекс: 31.06%
разработка игр: 30.37%


# **Вариант 2: тут добавили эпох, покрутили параметры обучения(лернинг рейт и тд) и немного изменили балансировку весов для хабов**

In [ ]:
counts = labels_matrix.sum(axis=0)
total_samples = len(labels_matrix)
pos_weights = (total_samples - counts) / (counts + 1e-5)
pos_weights = np.clip(pos_weights, 1, 15) # Снизили с 50 до 15!
pos_weights_tensor = torch.tensor(pos_weights, dtype=torch.float).to("cuda")

In [ ]:
class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")
        loss_fct = nn.BCEWithLogitsLoss(pos_weight=pos_weights_tensor)
        loss = loss_fct(logits, labels)
        return (loss, outputs) if return_outputs else loss

In [4]:
training_args = TrainingArguments(
    output_dir='./results_quality',
    num_train_epochs=5,
    per_device_train_batch_size=16,
    gradient_accumulation_steps=2,
    fp16=True,
    learning_rate=5e-5,             
    lr_scheduler_type="cosine", 
    warmup_steps=1000,
    eval_strategy="steps", 
    eval_steps=500,
    save_strategy="steps",
    save_steps=500,
    load_best_model_at_end=True,
    metric_for_best_model="loss",
    logging_strategy="steps",
    logging_steps=200,
    disable_tqdm=False,
    log_level="info",
    save_total_limit=2,
    report_to="none"
)

trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset
)

trainer.train()


login("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")
repo_id = "Yalmess/habr-e5-classifier_quality"
model.push_to_hub(repo_id)
tokenizer.push_to_hub(repo_id)

***** Running training *****
  Num examples = 70,183
  Num Epochs = 5
  Instantaneous batch size per device = 16
  Training with DataParallel so batch size has been adjusted to: 32
  Total train batch size (w. parallel, distributed & accumulation) = 64
  Gradient Accumulation steps = 2
  Total optimization steps = 5,485
  Number of trainable parameters = 117,818,925

***** Running Evaluation *****
  Num examples = 1000
  Batch size = 16
Saving model checkpoint to ./results_quality/checkpoint-500
Configuration saved in ./results_quality/checkpoint-500/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in ./results_quality/checkpoint-500/model.safetensors

***** Running Evaluation *****
  Num examples = 1000
  Batch size = 16
Saving model checkpoint to ./results_quality/checkpoint-1000
Configuration saved in ./results_quality/checkpoint-1000/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in ./results_quality/checkpoint-1000/model.safetensors

***** Running Evaluation *****
  Num examples = 1000
  Batch size = 16
Saving model checkpoint to ./results_quality/checkpoint-1500
Configuration saved in ./results_quality/checkpoint-1500/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in ./results_quality/checkpoint-1500/model.safetensors
Deleting older checkpoint [results_quality/checkpoint-500] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 1000
  Batch size = 16
Saving model checkpoint to ./results_quality/checkpoint-2000
Configuration saved in ./results_quality/checkpoint-2000/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in ./results_quality/checkpoint-2000/model.safetensors
Deleting older checkpoint [results_quality/checkpoint-1000] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 1000
  Batch size = 16
Saving model checkpoint to ./results_quality/checkpoint-2500
Configuration saved in ./results_quality/checkpoint-2500/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in ./results_quality/checkpoint-2500/model.safetensors
Deleting older checkpoint [results_quality/checkpoint-1500] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 1000
  Batch size = 16
Saving model checkpoint to ./results_quality/checkpoint-3000
Configuration saved in ./results_quality/checkpoint-3000/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in ./results_quality/checkpoint-3000/model.safetensors
Deleting older checkpoint [results_quality/checkpoint-2000] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 1000
  Batch size = 16
Saving model checkpoint to ./results_quality/checkpoint-3500
Configuration saved in ./results_quality/checkpoint-3500/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in ./results_quality/checkpoint-3500/model.safetensors
Deleting older checkpoint [results_quality/checkpoint-2500] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 1000
  Batch size = 16
Saving model checkpoint to ./results_quality/checkpoint-4000
Configuration saved in ./results_quality/checkpoint-4000/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in ./results_quality/checkpoint-4000/model.safetensors
Deleting older checkpoint [results_quality/checkpoint-3000] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 1000
  Batch size = 16
Saving model checkpoint to ./results_quality/checkpoint-4500
Configuration saved in ./results_quality/checkpoint-4500/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in ./results_quality/checkpoint-4500/model.safetensors
Deleting older checkpoint [results_quality/checkpoint-3500] due to args.save_total_limit

***** Running Evaluation *****
  Num examples = 1000
  Batch size = 16
Saving model checkpoint to ./results_quality/checkpoint-5000
Configuration saved in ./results_quality/checkpoint-5000/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in ./results_quality/checkpoint-5000/model.safetensors
Deleting older checkpoint [results_quality/checkpoint-4000] due to args.save_total_limit
Saving model checkpoint to ./results_quality/checkpoint-5485
Configuration saved in ./results_quality/checkpoint-5485/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in ./results_quality/checkpoint-5485/model.safetensors
Deleting older checkpoint [results_quality/checkpoint-4500] due to args.save_total_limit


Training completed. Do not forget to share your model on huggingface.co/models =)


Loading best model from ./results_quality/checkpoint-5000 (score: 0.22326470911502838).
There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

Загрузка модели в репозиторий Yalmess/habr-e5-classifier_quality...

Configuration saved in /tmp/tmpmlrczn8k/config.json

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model weights saved in /tmp/tmpmlrczn8k/model.safetensors
Uploading the following files to Yalmess/habr-e5-classifier_quality: config.json,README.md,model.safetensors

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

README.md: 0.00B [00:00, ?B/s]

tokenizer config file saved in /tmp/tmp8g5u21i3/tokenizer_config.json
Uploading the following files to Yalmess/habr-e5-classifier_quality: tokenizer.json,tokenizer_config.json,README.md

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

Готово! Теперь твоя модель живет на Hugging Face.

In [1]:
# !rm -rf /kaggle/working/*

In [22]:
MODEL_NAME = "Yalmess/habr-e5-classifier_quality"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME).to(DEVICE)

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [24]:
evaluate_fasttext_style(model, val_texts, val_labels, tokenizer)

  0%|          | 0/63 [00:00<?, ?it/s]

Precision@1: 0.3920
Recall@1:    0.1313
Jaccard@3:   0.1663

In [23]:
def predict_hubs(text, model, tokenizer, mlb, threshold=0.3):
    model.eval()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    text_prepared = "query: " + str(text)[:3000]
    inputs = tokenizer(
        text_prepared, 
        return_tensors="pt", 
        truncation=True, 
        padding='max_length', 
        max_length=512
    ).to(device)
    
    with torch.no_grad():
        outputs = model(**inputs)
        probs = torch.sigmoid(outputs.logits).cpu().numpy()[0]
    predicted_indices = [i for i, p in enumerate(probs) if p > threshold]
    if not predicted_indices:
        predicted_indices = [np.argmax(probs)]
    result_matrix = np.zeros((1, len(mlb.classes_)))
    for idx in predicted_indices:
        result_matrix[0, idx] = 1       
    predicted_labels = mlb.inverse_transform(result_matrix)[0]
    sorted_res = sorted(
        [(mlb.classes_[i], probs[i]) for i in predicted_indices], 
        key=lambda x: x[1], 
        reverse=True
    )
    
    return sorted_res

sample_text = """
Сегодня мы разберем, как развернуть контейнеры Docker в облаке AWS с использованием Terraform. 
Мы напишем конфигурацию для кластера Kubernetes (EKS) и настроим CI/CD через GitHub Actions.
"""
results = predict_hubs(sample_text, model, tokenizer, mlb, threshold=0.3)
for hub, prob in results:
    print(f"{hub}: {prob:.2%}")

системное администрирование: 77.41%
веб-разработка: 71.55%
информационная безопасность: 69.71%
devops: 68.28%
javascript: 66.25%
open source: 64.09%
it-инфраструктура: 62.05%
прочее: 58.13%
программирование: 57.76%
серверное администрирование: 56.19%
разработка мобильных приложений: 47.73%
kubernetes: 47.65%
android: 46.68%
java: 44.56%
ios: 41.76%
*nix: 41.64%
блог компании ruvds.com: 40.88%
сетевые технологии: 40.38%
php: 40.21%
настройка linux: 39.30%
облачные сервисы: 38.77%
linux: 38.68%
софт: 38.67%
базы данных: 37.31%
блог компании otus: 36.91%
.net: 36.42%
конференции: 36.04%
тестирование it-систем: 36.03%
высоконагруженные системы: 35.25%
виртуализация: 34.91%
хранение данных: 34.67%
браузеры: 33.88%
postgresql: 32.45%
тестирование веб-сервисов: 32.45%
c#: 32.06%
c++: 30.74%
sql: 30.25%

In [6]:
def get_predictions(model, dataset, batch_size=32):
    model.eval()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    
    all_probs = []
    all_labels = []
    
    with torch.no_grad():
        for i in tqdm(range(0, len(dataset), batch_size)):
            # Извлекаем батч из датасета
            batch_input_ids = []
            batch_target_labels = []
            
            for j in range(i, min(i + batch_size, len(dataset))):
                item = dataset[j]
                batch_input_ids.append(item['input_ids'])
                batch_target_labels.append(item['labels'])
            
            # Стакаем в тензоры
            input_ids = torch.stack(batch_input_ids).to(device)
            labels = torch.stack(batch_target_labels).numpy()
            
            # Прогон через модель
            outputs = model(input_ids)
            logits = outputs.logits
            # Получаем вероятности через сигмоиду
            probs = torch.sigmoid(logits).cpu().numpy()
            
            all_probs.append(probs)
            all_labels.append(labels)
            
    return np.vstack(all_probs), np.vstack(all_labels)

y_probs, y_true = get_predictions(model, val_dataset)
best_threshold = 0.3
best_jaccard = 0
thresholds = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

for t in thresholds:
    y_pred = (y_probs > t).astype(int)
    score = jaccard_score(y_true, y_pred, average='samples', zero_division=0)
    print(f"Threshold: {t:.1f} | Jaccard Score: {score:.4f}")
    
    if score > best_jaccard:
        best_jaccard = score
        best_threshold = t

print(f"\топ порог: {best_threshold} (жаккард={best_jaccard:.4f})")

print(f"\n---Threshold {best_threshold} ---")
final_preds = (y_probs > best_threshold).astype(int)
report = classification_report(
    y_true, 
    final_preds, 
    target_names=mlb.classes_, 
    zero_division=0,
    digits=4
)
print("\n".join(report.split("\n")[-10:]))

  0%|          | 0/32 [00:00<?, ?it/s]

Threshold: 0.1 | Jaccard Score: 0.0367
Threshold: 0.2 | Jaccard Score: 0.0665
Threshold: 0.3 | Jaccard Score: 0.1010
Threshold: 0.4 | Jaccard Score: 0.1352
Threshold: 0.5 | Jaccard Score: 0.1607
Threshold: 0.6 | Jaccard Score: 0.1641
Threshold: 0.7 | Jaccard Score: 0.1375
Threshold: 0.8 | Jaccard Score: 0.0655
\топ порог: 0.6 (жаккард=0.1641)

---Threshold 0.6 ---
                                     электроника для начинающих     0.0000    0.0000    0.0000         7
                                     энергия и элементы питания     0.0000    0.0000    0.0000        14
                                                      я пиарюсь     0.0000    0.0000    0.0000         1
                                                     яндекс api     0.0000    0.0000    0.0000         0

                                                      micro avg     0.2275    0.2693    0.2466      3327
                                                      macro avg     0.0259    0.0492    0.0289      3327
                                                   weighted avg     0.1311    0.2693    0.1615      3327
                                                    samples avg     0.2543    0.2879    0.2480      3327

# **Вариант 3 максимальный**

In [ ]:
counts = labels_matrix.sum(axis=0)
total_samples = len(labels_matrix)
pos_weights = (total_samples - counts) / (counts + 1e-5)
pos_weights = np.clip(pos_weights, 1, 5)
pos_weights_tensor = torch.tensor(pos_weights, dtype=torch.float).to("cuda")

In [ ]:
class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")
        loss_fct = nn.BCEWithLogitsLoss(pos_weight=pos_weights_tensor)
        loss = loss_fct(logits, labels)
        return (loss, outputs) if return_outputs else loss

In [6]:
training_args = TrainingArguments(
    output_dir='./results_long_run',
    num_train_epochs=10,
    per_device_train_batch_size=16,
    gradient_accumulation_steps=2,
    learning_rate=2e-5,
    lr_scheduler_type="cosine",
    warmup_steps=1500,
    fp16=True,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    save_total_limit=1,
    logging_steps=500,
    report_to="none"
)


trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

trainer.train()


login("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")
repo_id = "Yalmess/habr-e5-classifier_quality_big"
model.push_to_hub(repo_id)
tokenizer.push_to_hub(repo_id)

Начинаем марафон на 10 эпох...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

README.md: 0.00B [00:00, ?B/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

done

In [25]:
MODEL_NAME = "Yalmess/habr-e5-classifier_quality_big"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME).to(DEVICE)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [28]:

evaluate_fasttext_style(model, val_texts, val_labels, tokenizer)

  0%|          | 0/63 [00:00<?, ?it/s]

Precision@1: 0.2930
Recall@1:    0.0976
Jaccard@3:   0.1227

In [5]:
sample_text = """
Сегодня мы разберем, как развернуть контейнеры Docker в облаке AWS с использованием Terraform. 
Мы напишем конфигурацию для кластера Kubernetes (EKS) и настроим CI/CD через GitHub Actions.
"""

results = predict_hubs(sample_text, model, tokenizer, mlb, threshold=0.3)

Результат предсказания:
программирование: 57.37%
прочее: 53.91%
веб-разработка: 45.66%
javascript: 39.27%
системное администрирование: 38.17%
devops: 32.99%
it-инфраструктура: 30.11%